apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: green-cluster
  region: us-east-2

nodeGroups:
  - name: ng-green
    instanceType: t2.small    
    desiredCapacity: 1
    ssh:
        publicKeyPath: JenkinsS3
        allow: true
